function report = verifyQualityModel(outputPath)
%VERIFYQUALITYMODEL Check candidate ONNX and end-to-end preprocessing parity.

    baseDir = fileparts(mfilename('fullpath'));
    if nargin < 1
        outputPath = fullfile(baseDir, 'results', ...
            'quality_model_candidate_parity.json');
    end
    addpath(genpath(fullfile(baseDir, 'src')));
    [net, config] = loadQualityModel( ...
        fullfile(baseDir,'models','quality_model_candidate.onnx'), ...
        fullfile(baseDir,'models','quality_model_candidate.json'));
    fixture = load(fullfile(baseDir,'models','quality_parity_fixture.mat'));
    [rawClass, ~, rawLogits] = predictImageQuality(net, fixture.model_input, config);
    rawError = max(abs(rawLogits-double(fixture.expected_logits(:)')));
    reference = jsondecode(fileread( ...
        fullfile(baseDir,'models','quality_parity_reference.json')));
    image = imread(fullfile(fileparts(baseDir), reference.image_relative_to_project));
    candidateInput = preprocessQualityModelInput(image, config);
    inputError = max(abs(candidateInput-single(fixture.model_input)), [], 'all');
    [candidateClass, probabilities, candidateLogits] = ...
        predictImageQuality(net, candidateInput, config);
    endToEndError = max(abs(candidateLogits-double(reference.expected_logits(:)')));
    if rawError > 1e-4 || inputError > 1e-5 || endToEndError > 1e-3 || ...
            rawClass ~= double(fixture.expected_prediction) || ...
            candidateClass ~= double(reference.expected_prediction)
        error('NetrAI:QualityParityFailed', ...
            'Quality parity failed: raw %.6g, input %.6g, end-to-end %.6g.', ...
            rawError, inputError, endToEndError);
    end
    report = struct('passed',true,'raw_logit_error',rawError, ...
        'input_error',inputError,'end_to_end_logit_error',endToEndError, ...
        'quality_class',candidateClass,'probabilities',probabilities, ...
        'decision_match',candidateClass == double(reference.expected_prediction), ...
        'scope',"fixed real-image Python/ONNX/MATLAB parity fixture");
    outputFolder = fileparts(outputPath);
    if ~isfolder(outputFolder)
        mkdir(outputFolder);
    end
    writelines(jsonencode(report, PrettyPrint=true), outputPath);
    fprintf('Quality candidate MATLAB parity PASS | raw %.6g | input %.6g | end-to-end %.6g\n', ...
        rawError, inputError, endToEndError);
end
